[my_log_sourcetype]
FIELDALIAS-src = source_ip_addr AS src
FIELDALIAS-dest = dest_ip AS dest
FIELDALIAS-src_port = source_port AS src_port
FIELDALIAS-dest_port = dest_port AS dest_port
FIELDALIAS-action = action_taken AS action
FIELDALIAS-protocol = protocol_number AS protocol


[my_log_sourcetype]
FIELDALIAS-src = source_ip_addr AS src
FIELDALIAS-dest = dest_ip AS dest
FIELDALIAS-src_port = source_port AS src_port
FIELDALIAS-dest_port = dest_port AS dest_port
FIELDALIAS-action = action_taken AS action
FIELDALIAS-protocol = protocol_number AS protocol
